### ISSUE TITLE
not working at all on Gnome 3.28

### ISSUE THREAD

**Issue by fcastilloec** [fffilo/gnome-fuzzy-search#1]
I'm using Ubuntu 18.04.1 with Gnome 3.28.2, extension downloaded from [extensions.gnome.org](https://extensions.gnome.org/)

Once installed, and gnome restarted, this extension is preventing any results to appear on the search. In other words, neither the regular results nor the ones that this extension is supposed to add, are shown at all.

Also, under this extension settings, almost everything is grey out and can't be enabled, with the only exception of `Applications`. I was really looking forward to using this extension for files and documents and my calendar.

I tried to see if LookingGlass would show any errors but nothing there. If there's anything I can do to help fix this extension, do let me know. I really want this to work

**Comment by fffilo** [comment]
I currently use gnome 3.18.5 and haven't had the time (read: i was lazy) to test it on newer versions. I will test/fix it asap...

**Comment by fffilo** [comment]
Update...

    wget https://raw.githubusercontent.com/fffilo/gnome-fuzzy-search/master/install.sh -O - | bash

...and restart gnome shell. It should work now (?!)

Let me know.

**Comment by fcastilloec** [comment]
@fffilo the new commit on master fix the issue, at least the applications search, all the other settings are still greyed out. Is this because they haven't been implemented? or is this a bug?  I thought it might have been related to the original problem but it doesn't seem like that's the case. I can open a separate issue to deal with the greyed out settings if you prefer

**Comment by fffilo** [comment]
As mentioned in README

> This project is still work in progress, so for now you can only add fuzzy search results to AppSearchProvider.

Other providers will be added to extension when i find the time...

**Comment by fcastilloec** [comment]
I'm so sorry, my mistake. I didn't read the README to the end. I came from the gnome extensions page directly to the issues to see if this problem was already reported or not.
My bad...

**Comment by fffilo** [comment]
Don't worry about it.

I will try to find some time in near future and add fuzzy search to other providers...

Bye, F.
